# params.yaml
prepare:
  random_seed: 42
  
features:
  test_size: 0.2
  random_state: 42
  target_column: "price"
  
train:
  model_type: "RandomForest"
  n_estimators: 100
  max_depth: 10
  random_state: 42
  
evaluate:
  metrics: ["mae", "rmse", "r2"]